steps:
  # Back-end
  ## Run unit tests
  ## Downgrade Maven due to https://github.com/gleclaire/findbugs-maven-plugin/pull/35
  - name: maven:3.5.4-jdk-8-slim
    entrypoint: 'mvn'
    args: ['-f', 'relinkr-api', '-B', 'verify']
  ## Copy code coverage report to project's build bucket
  - name: gcr.io/cloud-builders/gsutil
    args: ['-m', 'rsync', '-r', '-d', 'relinkr-api/target/site/jacoco', 'gs://build.craftingjava.com/relinkr/jacoco']
  ## Copy code coverage badge to project's build bucket
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'relinkr-api/target/coverage.svg', 'gs://build.craftingjava.com/relinkr']
  # Front-end
  ## Compile
  - name: node:10.15.3
    entrypoint: npm
    args: ['run', 'build', '--prefix', 'relinkr-ui']
