server:
  port: 8443
  ssl:
    key-store: classpath:keystore-dev.p12
    key-store-password: mypassword
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  cloud:
    gcp:
      sql:
        enabled: false
  datasource:
    url: jdbc:postgresql://${PGSQL_HOST:localhost}:${PGSQL_PORT:5432}/${PGSQL_DB:relinkr}
