server:
  port: 8443
  ssl:
    key-store: classpath:keystore-development.p12
    key-store-password: mypassword
    key-store-type: PKCS12
    key-alias: tomcat
  use-forward-headers: false

spring:
  datasource:
    url: jdbc:postgresql://${PGSQL_HOST:localhost}:${PGSQL_PORT:5432}/${PGSQL_DB:relinkr}
  cloud:
    gcp:
      sql:
        enabled: false
